// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using login.Data;

#nullable disable

namespace login.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119103420_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("login.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("login.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("login.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik",
                            Slug = "elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilgisayar",
                            Slug = "bilgisayar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ev & Yaşam",
                            Slug = "ev-yasam"
                        });
                });

            modelBuilder.Entity("login.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "~/img/mouse.jpg",
                            Name = "Kablolu Mouse",
                            Price = 49.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ImageUrl = "~/img/klavye.jpg",
                            Name = "Mekanik Klavye",
                            Price = 349.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            ImageUrl = "~/img/bardak.jpg",
                            Name = "Bardak Seti",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageUrl = "~/img/images.png",
                            Name = "Bluetooth Kulaklık",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ImageUrl = "~/img/images.png",
                            Name = "Laptop Soğutucu",
                            Price = 269.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ImageUrl = "~/img/images.png",
                            Name = "Dekoratif Yastık",
                            Price = 59.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ImageUrl = "~/img/images.png",
                            Name = "Gaming Mousepad",
                            Price = 89.90m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            ImageUrl = "~/img/images.png",
                            Name = "Kahve Makinesi",
                            Price = 699.90m
                        });
                });

            modelBuilder.Entity("login.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("VerificationCodeExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("verificationCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            IsEmailConfirmed = true,
                            Password = "1234",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("login.Models.CartItem", b =>
                {
                    b.HasOne("login.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("login.Models.Product", b =>
                {
                    b.HasOne("login.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("login.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("login.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
